routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BlogController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('blogs', 'BlogController');

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    //
    public function user()
    {
        return $this->belongsTo('App\User')->select(['id', 'name', 'photo', 'email']);
    }


}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $blogs = Blog::all();
        return view('blog.index')->with(['blogs' => $blogs]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        if(Auth::id() == null) {
            return redirect('login');
        } else {
            return view('blog.create');
        }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $title = $request->input('title');
        $summary = $request->input('summary');
        $content = $request->input('content');
        $user_id = Auth::id();

        $cover_img_path = "";
        if($request->file('cover_img') != null) {
            logger()->debug('cover img is not null');
            $cover_img_path = $request->file('cover_img')->store('uploads/cover-imgs', 'direct_public');
        }

        $blog = new Blog();
        $blog->title = $title;
        $blog->summary = $summary;
        $blog->content = $content;
        $blog->user_id = $user_id;
        if($cover_img_path != "") $blog->cover_img = $cover_img_path;

        $blog->save();

        return redirect('blogs')->with('success', '成功建立文章');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = Blog::find($id);
        if($blog == null) {
            return redirect('blogs')->with('error', '找不到文章');
        }
        return view('blog.detail')->with('blog', $blog);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        logger()->debug('edit blog with id :' . $id);
        $blog = Blog::find($id);
        $user_id = Auth::id();
        if($blog->user_id != $user_id) {
            return redirect('blogs')->with('error', '你沒有權限編輯這篇文章');
        }
        return view('blog.edit')->with(['blog' => $blog]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        logger()->debug('update blog with id :' . $id);

        $title = $request->input('title');
        $summary = $request->input('summary');
        $content = $request->input('content');
        $user_id = Auth::id();

        $blog = Blog::find($id);

        if($blog->user_id != $user_id) {
            return redirect('blogs')->with('error', '你沒有權限編輯這篇文章');
        }

        $cover_img_path = "";
        if($request->file('cover_img') != null) {
            logger()->debug('cover img is not null');
            $cover_img_path = $request->file('cover_img')->store('uploads/cover-imgs', 'direct_public');
        }

        if($title != "") $blog->title = $title;
        if($summary != "") $blog->summary = $summary;
        if($content != "") $blog->content = $content;
        if($cover_img_path != "") $blog->cover_img = $cover_img_path;

        $blog->save();

        return redirect('blogs')->with('success', '成功更新文章');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        logger()->debug('going to delete post with id :' . $id);
        // check if user owns this post
        $user_id = Auth::id();
        $blog = Blog::find($id);
        if($blog->user_id == $user_id) {
            $blog->delete();
            return redirect('/')->with('success', '成功刪除文章');
        } else {
            // throw error msg
            return redirect('/')->with('error', '你沒有權限刪除這篇文章');
        }

    }

    public function apiList(Request $request) {
        $blogs = Blog::orderBy('created_at', 'desc')->with('user')->get();
        return response()->json(
          [
              'success' => 1,
              'blogs' => $blogs
          ]
        );
    }


    public function apiDetail($id) {

        $blog = Blog::where('id', '=', $id)->with('user')->first();

        return response()->json(
            [
                'success' => 1,
                'blog' => $blog
            ]
        );


    }


    public function apiStore(Request $request) {

        $token = $request->input('token');
        $user_id = $request->input('user_id');
        $title = $request->input('title');
        $summary = $request->input('summary');
        $content = $request->input('content');

        $validator = Validator::make($request->all(), [
            'user_id' => 'required',
            'token' => 'required',
            'title' => 'required',
            'content' => 'required',
            'cover_img' => 'required|image|mimes:jpeg,png,jpg|max:2048'
        ]);

        if ($validator->fails()) {
            return response()->json(
                [
                    'success' => 0,
                    'error_msg' => $validator->errors()
                ]
            );
        }

        $user = User::where('id', '=', $user_id)->where('api_token', '=', $token)->first();
        if($user == null) {
            return response()->json(
                [
                    'success' => 0,
                    'error_msg' => 'invalid user'
                ]
            );
        }

        $cover_img_path = $request->file('cover_img')->store('uploads/cover-imgs', 'direct_public');

        $blog = new Blog();
        $blog->user_id = $user_id;
        $blog->title = $title;
        $blog->summary = $summary;
        $blog->content = $content;
        $blog->cover_img = $cover_img_path;
        $blog->save();

        return response()->json(
            [
                'success' => 1,
                'blog' => $blog
            ]
        );

    }


    public function apiUpdate(Request $request) {

        $token = $request->input('token');
        $user_id = $request->input('user_id');
        $blog_id = $request->input('blog_id');
        $title = $request->input('title');
        $summary = $request->input('summary');
        $content = $request->input('content');

        $validator = Validator::make($request->all(), [
            'user_id' => 'required',
            'token' => 'required',
            'blog_id' => 'required',
        ]);

        if ($validator->fails()) {
            return response()->json(
                [
                    'success' => 0,
                    'error_msg' => $validator->errors()
                ]
            );
        }

        $user = User::where('id', '=', $user_id)->where('api_token', '=', $token)->first();
        if($user == null) {
            return response()->json(
                [
                    'success' => 0,
                    'error_msg' => 'invalid user'
                ]
            );
        }

        $blog = Blog::where('user_id', '=', $user_id)->where('id', '=', $blog_id)->first();
        if($blog == null) {
            return response()->json(
                [
                    'success' => 0,
                    'error_msg' => 'invalid blog'
                ]
            );
        }

        $cover_img_path = "";
        if($request->file('cover_img') != null) {
            $cover_img_path = $request->file('cover_img')->store('uploads/cover-imgs', 'direct_public');
        }


        if($title != null) $blog->title = $title;
        if($summary != null) $blog->summary = $summary;
        if($content != null) $blog->content = $content;
        if($cover_img_path != "") $blog->cover_img = $cover_img_path;

        $blog->save();

        return response()->json(
            [
                'success' => 1,
                'blog' => $blog
            ]
        );

    }

    public function apiDelete(Request $request) {

        $token = $request->input('token');
        $user_id = $request->input('user_id');
        $blog_id = $request->input('blog_id');

        $validator = Validator::make($request->all(), [
            'user_id' => 'required',
            'token' => 'required',
            'blog_id' => 'required',
        ]);

        if ($validator->fails()) {
            return response()->json(
                [
                    'success' => 0,
                    'error_msg' => $validator->errors()
                ]
            );
        }

        $user = User::where('id', '=', $user_id)->where('api_token', '=', $token)->first();
        if($user == null) {
            return response()->json(
                [
                    'success' => 0,
                    'error_msg' => 'invalid user'
                ]
            );
        }

        $blog = Blog::where('user_id', '=', $user_id)->where('id', '=', $blog_id)->first();
        if($blog == null) {
            return response()->json(
                [
                    'success' => 0,
                    'error_msg' => 'invalid blog'
                ]
            );
        }

        $blog->delete();

        return response()->json(
            [
                'success' => 1
            ]
        );



    }

}

resources/views/blog/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Becca's Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="/startbootstrap-clean-blog/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/startbootstrap-clean-blog/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="/startbootstrap-clean-blog/css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
@include('common.nav')

<!-- Page Header -->
<header class="masthead" style="background-image: url('startbootstrap-clean-blog/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Becca's Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">


            <form action="/blogs" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="title">標題</label>
                    <input type="input" class="form-control" id="title" placeholder="enter title" name="title">
                </div>

                <div class="form-group">
                    <label for="summary">封面圖</label>
                    <input type="file" class="form-control" id="cover_img" name="cover_img">
                </div>

                <div class="form-group">
                    <label for="summary">簡述</label>
                    <textarea rows="3" class="form-control" id="summary" placeholder="enter summary" name="summary"></textarea>
                </div>

                <div class="form-group">
                    <label for="content">內文</label>
                    <textarea rows="5" class="form-control" id="content" placeholder="enter content" name="content"></textarea>
                </div>

                <button type="submit" class="btn btn-primary">新增文章</button>
            </form>

        </div>
    </div>
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="/startbootstrap-clean-blog/vendor/jquery/jquery.min.js"></script>
<script src="/startbootstrap-clean-blog/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Custom scripts for this template -->
<script src="/startbootstrap-clean-blog/js/clean-blog.min.js"></script>

</body>

</html>

resources/views/blog/detail.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Becca's Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="/startbootstrap-clean-blog/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/startbootstrap-clean-blog/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="/startbootstrap-clean-blog/css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
@include('common.nav')

        <!-- Page Header -->
<header class="masthead" style="background-image: url('/startbootstrap-clean-blog/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Becca's Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
                <div class="post-preview">
                    @if(Auth::id() == $blog->user_id)
                        <div class="float-right">
                            <div class="btn-group" role="group">
                                <form action="{{route('blogs.edit', ['blog' => $blog->id])}}" method="get">
                                    <button type="submit" class="btn btn-outline-light"><i class="fa fa-edit text-success"></i></button>
                                </form>
                                <form action="{{route('blogs.destroy', ['blog' => $blog->id])}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-outline-light" onclick="return confirm('文章會被永久刪除，你確定要刪除文章嗎？');"><i class="fa fa-trash text-danger"></i></button>
                                </form>
                            </div>
                        </div>
                    @endif

                    <h2 class="post-title">
                        {{$blog->title}}
                    </h2>

                    @if($blog->cover_img != null)
                        <div>
                            <img src="/{{$blog->cover_img}}" style="" class="img-fluid img-thumbnail">
                            <p></p>
                        </div>
                    @endif

                    <p class="post-meta">Posted by
                        <a href="#">{{$blog->user->name}}</a> on {{$blog->created_at}}
                    </p>
                    <div>
                        {{$blog->content}}
                    </div>
                </div>
                <hr>

        </div>
    </div>
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="startbootstrap-clean-blog/vendor/jquery/jquery.min.js"></script>
<script src="startbootstrap-clean-blog/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Custom scripts for this template -->
<script src="startbootstrap-clean-blog/js/clean-blog.min.js"></script>

</body>

</html>

resources/views/blog/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Becca's Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="/startbootstrap-clean-blog/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/startbootstrap-clean-blog/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="/startbootstrap-clean-blog/css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
@include('common.nav')

        <!-- Page Header -->
<header class="masthead" style="background-image: url('/startbootstrap-clean-blog/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Becca's Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">


            <form action="/blogs/{{$blog->id}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="title">標題</label>
                    <input type="input" class="form-control" id="title" placeholder="enter title" name="title" value="{{$blog->title}}">
                </div>

                <div class="form-group">
                    <label for="summary">封面圖</label>
                    @if($blog->cover_img != "")
                        <img class="col-lg-4" src="/{{$blog->cover_img}}"><p></p>
                    @endif
                    <input type="file" class="form-control" id="cover_img" name="cover_img">

                </div>

                <div class="form-group">
                    <label for="summary">簡述</label>
                    <textarea rows="3" class="form-control" id="summary" placeholder="enter summary" name="summary">{{$blog->summary}}</textarea>
                </div>

                <div class="form-group">
                    <label for="content">內文</label>
                    <textarea rows="5" class="form-control" id="content" placeholder="enter content" name="content">{{$blog->content}}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">更新文章</button>
            </form>

        </div>
    </div>
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="/startbootstrap-clean-blog/vendor/jquery/jquery.min.js"></script>
<script src="/startbootstrap-clean-blog/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Custom scripts for this template -->
<script src="/startbootstrap-clean-blog/js/clean-blog.min.js"></script>

</body>

</html>

resources/views/blog/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Becca's Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="startbootstrap-clean-blog/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="startbootstrap-clean-blog/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="startbootstrap-clean-blog/css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
@include('common.nav')

<!-- Page Header -->
<header class="masthead" style="background-image: url('startbootstrap-clean-blog/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Becca's Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
            @foreach($blogs as $blog)
                <div class="post-preview">
                    @if(Auth::id() == $blog->user_id)
                        <div class="float-right">
                            <div class="btn-group" role="group">
                                <form action="{{route('blogs.edit', ['blog' => $blog->id])}}" method="get">
                                    <button type="submit" class="btn btn-outline-light"><i class="fa fa-edit text-success"></i></button>
                                </form>
                                <form action="{{route('blogs.destroy', ['blog' => $blog->id])}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-outline-light" onclick="return confirm('文章會被永久刪除，你確定要刪除文章嗎？');"><i class="fa fa-trash text-danger"></i></button>
                                </form>
                            </div>
                        </div>
                    @endif
                    <a href="/blogs/{{$blog->id}}">

                        <h2 class="post-title">
                            {{$blog->title}}
                        </h2>

                        @if($blog->cover_img != null)
                            <div>
                                <img src="/{{$blog->cover_img}}" style="" class="img-fluid img-thumbnail">
                                <p></p>
                            </div>
                        @endif
                        <h3 class="post-subtitle">
                            {{$blog->summary}}
                        </h3>
                    </a>
                    <p class="post-meta">Posted by
                        <a href="#">{{$blog->user->name}}</a> on {{$blog->created_at}}
                    </p>
                </div>
                <hr>

            @endforeach

            <!-- Pager -->
            <div class="clearfix">
                <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
            </div>
        </div>
    </div>
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="startbootstrap-clean-blog/vendor/jquery/jquery.min.js"></script>
<script src="startbootstrap-clean-blog/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Custom scripts for this template -->
<script src="startbootstrap-clean-blog/js/clean-blog.min.js"></script>

</body>

</html>